### ISSUE TITLE
您好，發現兩個錯字和閱讀體驗的問題

### ISSUE THREAD

**Issue by freedom5566** [twtrubiks/Git-Tutorials#1]
[這個段落](https://github.com/twtrubiks/Git-Tutorials/blob/master/README.md#%E6%96%B0%E5%BB%BA%E8%88%87-%E5%90%88%E4%BD%B5--merge--%E5%88%86%E6%94%AF-branch)

前兩行
```
`再`說明 分支 branch 之前，先給大家一個觀念。

通常`再`開發的時候，大家都是從 master 做一個 分支 branch 出去，最後再 merge 回 master
```
那兩個"再"，是否應該是"在"呢？或著直接去除掉也不影響意思，反而更加通順。 

另外我閱讀 README.md 時感到有點過長

不曉得是否能分段呢？

我的想法是 README.md 用來存放目錄連結，文章打散成多個 md 檔案，目錄連結可以連結到 md 檔。

目錄連結的地方也能補個大概說明每個連結介紹了哪些指令、概念等等。

這樣我想對新手、想找指令的使用者來說要看甚麼都一目了然 

一點意見，如果大大覺得不適合可以直接關閉沒關係。:)

**Comment by twtrubiks** [comment]
@freedom5566  真的非常感謝大大的幫助，你應該不是第一次幫我看錯字了。
雖然我自己都會看好幾遍，但難免會漏掉，真的感謝您 :thumbsup:

另外，關於文章太長這部分，原因是之前本來只是想拿來當作筆記，就如果要查關鍵字，Ctrl+F 就可以很快找到我要的東西，如果拆成很多部分，反正會不好快速的找到我要的關鍵字，所以就會像你現在看到的一樣越來越長XDDD

有考慮過 gitbook，但還在評估中，總之，感謝您的建議:innocent:

**Comment by freedom5566** [comment]
@twtrubiks 大大也不是第一次寫教學文章拍教學影片貢獻了哈哈哈哈哈
不用怕錯字，GitHub有小精靈會幫你抓/修(咦)，專心在內容就好!!
我有從中得到收穫，很感謝你的付出!

謝謝大大回覆，這樣我了解了!!

**Comment by twtrubiks** [comment]
修正了，感謝提醒 https://github.com/twtrubiks/Git-Tutorials/commit/aa5ac25df42278ea39bfe65fe0361d0f1e646743
