### ISSUE TITLE
using several git programs simultaneously

### ISSUE THREAD

**Issue by AtomicNess123** [twtrubiks/Git-Tutorials#3]
I have a question of a basic nature. I was working with SourceTree in a local repo pushing to Github.com. At some point I decided to use Github Desktop, so I added the local repo and started to push to Github.com. I did not like this software, so I went back to SourceTree. Opened my project there but changes were not being tracked anymore. I wonder if one can use two git managers for tracking changes or else I don't know what went wrong.

**Comment by twtrubiks** [comment]
Hi ~
You need to read your error message to solve it.
This demand is theoretically feasible

**Comment by AtomicNess123** [comment]
There was actually no error. It just stopped tracking. Last thing I remember was that when I opened Github (after using SourceTree), it asked me to initialize a git repository where there was already one (which surprised me since a .git was already there) and I selected yes. So this may have reset the whole git tracking?

**Comment by twtrubiks** [comment]
try git remote -v , check remote.  or delete .git folder

**Comment by AtomicNess123** [comment]
Thanks
